### ISSUE TITLE
Example not showing ASM golay decoder

### ISSUE THREAD

**Issue by sferaud973** [mndza/gr-sattools#4]
Hi!

I have downloaded your library and I am trying to run the example that you give. However, there are some blocks missing when opening the example in gnuradio:

- sattools asm golay decoder
- sattols csp zmqhub pub sink

![gnuradio_asmgolayreciever](https://user-images.githubusercontent.com/49979694/56726298-c8791800-674e-11e9-8031-affaae8b8c37.png)

How can I fix this problem? How can I insert these missing blocks?

Thank you!

**Comment by mndza** [comment]
You would need to install these blocks first. 
Please follow the "manual build" steps from the README before opening the example file.

BTW, are you using the last commit? "Maximum Deviation" in the Symbol Sync block is now 0.01.
