### ISSUE TITLE
No module named 'sattools'

### ISSUE THREAD

**Issue by melfvelin** [mndza/gr-sattools#8]
When executing a flowgraph with the ASM + Golay Decoder block I get the following error message:
`Executing: /usr/bin/python3 -u /home/martin/rf_suit_1.py

```
Traceback (most recent call last):
  File "/home/martin/rf_suit_1.py", line 42, in <module>
    import sattools
ModuleNotFoundError: No module named 'sattools'

>>> Done (return code 1)

```
managed to work around it by setting PYTHONPATH=~/gr-sattools/include which then yields the following error:
`AttributeError: module 'sattools' has no attribute 'asm_golay_decoder'
`

**Comment by mndza** [comment]
Could you try do do this after install?
`sudo ldconfig`
Then restart GNURadio.

**Comment by melfvelin** [comment]
Still the same error

**Comment by mndza** [comment]
Are you using GNURadio from the Ubuntu repositories?
In that case, could you try to reinstall but using this modified install prefix?:
```
mkdir build/
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr ../
make -j4
sudo make install
```

**Comment by melfvelin** [comment]
Thank you for the quick help! The flowgraph now executes.

**Comment by mndza** [comment]
You're welcome! 
This install prefix problem is a very common one, but I have not found a way to handle this properly (this happens to me with other OOT modules too). I will add a note in the README file.
